<template>
	<h1>Custom Class</h1>

	<p>This plugin allows you to prefix Prism's default classes (‘.comment’ can become ‘.namespace--comment’) or
		replace
		them with your defined ones (like ‘.editor__comment’). You can even add new classes.</p>


	<h2>Motivation</h2>
	<p>Prism default classes are sensible but fixed and too generic. This plugin provide some ways to customize those
		classes to suit your needs. Example usages:</p>


	<p>You want to add namespace for all of them (like <code v-code.js>.prism--comment</code>) to avoid conflict
		with
		your existing classes.</p>

	<p>You use a naming convention (like BEM). You want to write classes like <code v-code.js>.editor__comment</code>.
		You use CSS Modules. You want to use your hashed classes, like <code v-code.js>.comment_7sh3a</code>.</p>

	<p>You need more granular control about the classes of certain tokens. You can define functions which will add new
		classes to tokens, so selectively change the highlighting of certain parts of your code.</p>



	<h2>How to use</h2>

	<p>Prefix all Prism classes</p>

	<pre>
			<code v-code.js>Prism.plugins.customClass.prefix('prism--')</code>
		</pre>


	<p>Replace some Prism classes with ones you defined</p>


	<pre>
<code v-code.js>
Prism.plugins.customClass.map({
  keyword: 'special-keyword',
  string: 'string_ch29s',
  comment: 'comment_93jsa'
})
</code>
		</pre>


	<p>Object's keys are the classes you want to replace (eg: <code v-code.js>comment</code>), with their values
		being the
		classes you want to use (eg: <code v-code.js>my-comment</code>). Classes which are not specified will stay as
		they
		are.</p>


	<p>Alternatively you can also pass a function that takes the original class and returns the mapped class. This
		function can also be used implement language specific mapped classes.
		Example:</p>


	<pre>
<code v-code.js>
	Prism.plugins.customClass.map((className, language) => {
  if (language === 'css') {
    return cssSpecificMap[className] || className
  } else {
    return className
  }
})
</code>
</pre>


	<h2>Add new classes</h2>


	<p>You can add new classes with per-token and per-language precision.</p>


	<pre>
<code v-code.js>
	Prism.plugins.customClass.add(({content, type, language}) => {
  if (content === 'content' && type === 'property' && language === 'css') {
    return 'content-property'
  }
})
</code>
</pre>


	<p>Note: The given ‘content’ is the inner HTML of the current token. All ‘&lt;’ and ‘&lt;’ characters are escaped and
		it might contain the HTML code of nested tokens.</p>


	<h2>Notes</h2>


	<p>Feature functions must be called <strong>AFTER</strong> Prism and this plugin. For example:</p>


	<pre>
<code v-code.html>
	&lt;!-- 1. load prism --&gt;
&lt;script src="prism.js"&gt;&lt;/script&gt;
&lt;!-- 2. load the plugin if you don't include it inside prism when download --&gt;
&lt;script src="plugins/custom-class/custom-class.js"&gt;&lt;/script&gt;
&lt;!-- 3. call the feature you want to use --&gt;
&lt;script&gt;
	Prism.plugins.customClass.map(myClassMap);
	Prism.plugins.customClass.prefix(myPrefixString);
&lt;/script&gt;
</code>
	</pre>

	<p>In most cases, using 1 feature is enough. However, it is possible to use both of them together if you want (Result
		will be like <code v-code.js>.my-namespace--comment_93jsa</code>).</p>



	<h3>CSS Modules Usage:</h3>


	<p>The initial purpose of this plugin is to be used with CSS Modules. It works perfectly with the class map object
		returned by CSS Modules. For example:</p>

	<pre>
<code v-code.js>
	import Prism from 'prismjs'
import classMap from 'styles/editor-class-map.css'

Prism.plugins.customClass.map(classMap)
</code>
		</pre>


	<p>Note: This plugin only affects generated token elements (usually of the form ‘span.token’). The classes of ‘code’
		and ‘pre’ elements as well as all elements generated by other plugins (e.g. <ins>Toolbar</ins> elements and
		<ins>line number</ins> elements) will not be changed.
	</p>

	<br>
	<hr>

	<h2>Example</h2>

	<br>
	<h4>Prefix and map classes</h4>



	<p>Input</p>

	<pre>

<code v-code.html>
	&lt;pre class="language-javascript"&gt;
	&lt;code&gt;
		var foo = 'bar';
	&lt;/code&gt;
&lt;/pre&gt;

</code>
	</pre>


	<p>Options</p>

	<pre>

<code v-code.js>
	Prism.plugins.customClass.map({
	keyword: 'special-keyword',
	string: 'my-string'
});

Prism.plugins.customClass.prefix('pr-');

</code>
</pre>

	<p>Output</p>


	<pre>

<code v-code.html>
	&lt;pre class="language-javascript"&gt;
	&lt;code class="language-markup"&gt;
		&lt;span class="pr-token pr-special-keyword"&gt;var&lt;/span&gt;
		foo
		&lt;span class="pr-token pr-operator"&gt;=&lt;/span&gt;
		&lt;span class="pr-token pr-my-string"&gt;'bar'&lt;/span&gt;
		&lt;span class="pr-token pr-punctuation"&gt;;&lt;/span&gt;
	&lt;/code&gt;
&lt;/pre&gt;

</code>
</pre>

	<p>Note that this plugin only affects tokens. The classes of the ‘code’ and ‘pre’ elements won't be prefixed.</p>


	<br>


	<h4>Add new classes</h4>


	<p>Input</p>


	<pre>

<code v-code.html>
	&lt;pre class="language-css"&gt;
	&lt;code&gt;
		a::after {
			content: '\2b00 ';
			opacity: .7;
		}
	&lt;/code&gt;
&lt;/pre&gt;
</code>

	</pre>

	<p>Options</p>


	<pre>
<code v-code.js>
	Prism.plugins.customClass.add(({language, type, content}) => {
	if (content === 'content' && type === 'property' && language === 'css') {
		return 'content-property'
	}
})
</code>
	</pre>

	<p>Output</p>


	<pre>

<code v-code.html>
	&lt;pre class=" language-css"&gt;
	&lt;code class=" language-css"&gt;
		&lt;span class="token selector"&gt;a::after&lt;/span&gt;
		&lt;span class="token punctuation"&gt;{&lt;/span&gt;
			&lt;span class="token property content-property"&gt;content&lt;/span&gt;
			&lt;span class="token punctuation"&gt;:&lt;/span&gt;
			&lt;span class="token string"&gt;'\2b00 '&lt;/span&gt;
			&lt;span class="token punctuation"&gt;;&lt;/span&gt;
			&lt;span class="token property"&gt;opacity&lt;/span&gt;
			&lt;span class="token punctuation"&gt;:&lt;/span&gt;
			.7
			&lt;span class="token punctuation"&gt;;&lt;/span&gt;
		&lt;span class="token punctuation"&gt;}&lt;/span&gt;
	&lt;/code&gt;
&lt;/pre&gt;

</code>
	</pre>
</template>