<template>
	<h1>文本格式化标签</h1>


	<table>
		<tr>
			<th>标签</th>
			<th>描述</th>
		</tr>
		<tr>
			<td>&lt;b&gt;</td>
			<td>定义粗体文本。</td>
		</tr>
		<tr>
			<td>&lt;strong&gt;</td>
			<td>定义语气更为强烈的强调文本。</td>
		</tr>
		<tr>
			<td>&lt;i&gt;</td>
			<td>定义斜体文本。</td>
		</tr>
		<tr>
			<td>&lt;em&gt;</td>
			<td>定义强调文本。</td>
		</tr>
		<tr>
			<td>&lt;u&gt;</td>
			<td>定义下划线文本。</td>
		</tr>
		<tr>
			<td>&lt;ins&gt;</td>
			<td>定义被插入文本。</td>
		</tr>
		<tr>
			<td>&lt;s&gt;</td>
			<td>定义加删除线的文本。</td>
		</tr>
		<tr>
			<td>&lt;del&gt;</td>
			<td>定义被删除文本。</td>
		</tr>
		<tr>
			<td>&lt;sub&gt;</td>
			<td>定义下标文本。</td>
		</tr>
		<tr>
			<td>&lt;sup&gt;</td>
			<td>定义上标文本。</td>
		</tr>
		<tr>
			<td>&lt;mark&gt;</td>
			<td>定义带有记号的文本。(被标记的/高亮显示的文本)</td>
		</tr>
		<tr>
			<td>&lt;small&gt;</td>
			<td>定义小号文本。</td>
		</tr>
		<tr>
			<td>&lt;wbr&gt;</td>
			<td>规定在文本中的何处适合添加换行符。</td>
		</tr>
	</table>
</template>